// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGtOHv2b5nu-28rZHGu1lYmNjQe_Nqes',
    appId: '1:461584909598:web:9a5d5b264c3519e4d4b50f',
    messagingSenderId: '461584909598',
    projectId: 'zarstravel-ea098',
    authDomain: 'zarstravel-ea098.firebaseapp.com',
    storageBucket: 'zarstravel-ea098.appspot.com',
    measurementId: 'G-4QPCL6YJQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe8o8LW6W1JZQY4FQ-ar799Fj-koZsnRY',
    appId: '1:461584909598:android:f7c1d7769a37a5cdd4b50f',
    messagingSenderId: '461584909598',
    projectId: 'zarstravel-ea098',
    storageBucket: 'zarstravel-ea098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF8hFX5EBLy16Q92K_xeb7eWCl90hygjI',
    appId: '1:461584909598:ios:70ff74f86c9b5507d4b50f',
    messagingSenderId: '461584909598',
    projectId: 'zarstravel-ea098',
    storageBucket: 'zarstravel-ea098.appspot.com',
    iosBundleId: 'com.example.zarstravels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF8hFX5EBLy16Q92K_xeb7eWCl90hygjI',
    appId: '1:461584909598:ios:70ff74f86c9b5507d4b50f',
    messagingSenderId: '461584909598',
    projectId: 'zarstravel-ea098',
    storageBucket: 'zarstravel-ea098.appspot.com',
    iosBundleId: 'com.example.zarstravels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxGtOHv2b5nu-28rZHGu1lYmNjQe_Nqes',
    appId: '1:461584909598:web:b3a05ccae3931d04d4b50f',
    messagingSenderId: '461584909598',
    projectId: 'zarstravel-ea098',
    authDomain: 'zarstravel-ea098.firebaseapp.com',
    storageBucket: 'zarstravel-ea098.appspot.com',
    measurementId: 'G-GNXW2CCEH8',
  );

}